spring:

  cache:
    type:
      redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  application:
    name: consent.api

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/consent
    username: root
    password: 3571
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true


